namespace: open-cluster-management

resources:
- resources/clusterrole.yaml
- resources/controller.yaml

images:
- name: policy-controller
  newName: quay.io/open-cluster-management/policy-addon
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
