---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:{{ .AddonName }}
  labels:
    component: "policy"
subjects:
- kind: ServiceAccount
  name: policy
  namespace: {{ .AddonInstallNamespace }}
roleRef:
  kind: ClusterRole
  name: open-cluster-management:{{ .AddonName }}
  apiGroup: rbac.authorization.k8s.io
