---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:klusterlet-addon-policy
  labels:
    component: "policy"
subjects:
- kind: ServiceAccount
  name: policy
  namespace: open-cluster-management-agent-addon
roleRef:
  kind: ClusterRole
  name: open-cluster-management:klusterlet-addon-policy
  apiGroup: rbac.authorization.k8s.io
